# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: node_service.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'node_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12node_service.proto\x12\x0bnodeservice\"\x10\n\x0e\x44\x65\x66\x61ultRequest\"\x14\n\x06NodeId\x12\n\n\x02id\x18\x01 \x01(\x05\"\"\n\x0fResponseMessage\x12\x0f\n\x07message\x18\x01 \x01(\t\"R\n\x15UpdatePredSuccRequest\x12\x12\n\nidentifier\x18\x01 \x01(\x05\x12%\n\x07\x61\x64\x64ress\x18\x02 \x01(\x0b\x32\x14.nodeservice.Address\"M\n\x10JoinNodeResponse\x12\x12\n\nidentifier\x18\x01 \x01(\x05\x12%\n\x07\x61\x64\x64ress\x18\x02 \x01(\x0b\x32\x14.nodeservice.Address\"#\n\x07\x41\x64\x64ress\x12\n\n\x02ip\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\x05\x32\xd1\x04\n\x0bNodeService\x12\x43\n\x0bJoinNetwork\x12\x14.nodeservice.Address\x1a\x1c.nodeservice.ResponseMessage\"\x00\x12K\n\x0cLeaveNetwork\x12\x1b.nodeservice.DefaultRequest\x1a\x1c.nodeservice.ResponseMessage\"\x00\x12M\n\x0eGetFingerTable\x12\x1b.nodeservice.DefaultRequest\x1a\x1c.nodeservice.ResponseMessage\"\x00\x12J\n\x0bGetPredSucc\x12\x1b.nodeservice.DefaultRequest\x1a\x1c.nodeservice.ResponseMessage\"\x00\x12@\n\x08LookUpID\x12\x13.nodeservice.NodeId\x1a\x1d.nodeservice.JoinNodeResponse\"\x00\x12;\n\x0b\x43onnectPeer\x12\x14.nodeservice.Address\x1a\x14.nodeservice.Address\"\x00\x12H\n\x11UpdateFingerTable\x12\x1b.nodeservice.DefaultRequest\x1a\x14.nodeservice.Address\"\x00\x12L\n\x0eUpdatePredSucc\x12\".nodeservice.UpdatePredSuccRequest\x1a\x14.nodeservice.Address\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'node_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DEFAULTREQUEST']._serialized_start=35
  _globals['_DEFAULTREQUEST']._serialized_end=51
  _globals['_NODEID']._serialized_start=53
  _globals['_NODEID']._serialized_end=73
  _globals['_RESPONSEMESSAGE']._serialized_start=75
  _globals['_RESPONSEMESSAGE']._serialized_end=109
  _globals['_UPDATEPREDSUCCREQUEST']._serialized_start=111
  _globals['_UPDATEPREDSUCCREQUEST']._serialized_end=193
  _globals['_JOINNODERESPONSE']._serialized_start=195
  _globals['_JOINNODERESPONSE']._serialized_end=272
  _globals['_ADDRESS']._serialized_start=274
  _globals['_ADDRESS']._serialized_end=309
  _globals['_NODESERVICE']._serialized_start=312
  _globals['_NODESERVICE']._serialized_end=905
# @@protoc_insertion_point(module_scope)
